### ISSUE TITLE
Can't exit <reference><refbody><section>  

### ISSUE THREAD

**Issue by Boreal-Forest** [dita4publishers/org.dita4publishers.word2dita#24]
Hi there, 

So far so great!  Except for one tiny little thing ...

My tag mapping  inserts `<section>`s  in a reference topic.  But then when I get to `<refsyn>` I want to exit the `<section>` so that `<refsyn>` is valid.  

Just can't seem to do it.  No idea why.  Level setting doesn't work.  Other level changing tricks don't see to work either.  

The attached ZIP includes the docx, the stylemap and the "out" I get.  

The offending style map definitions start after 
```
<!-- ===================================================================
     REFERENCE Styles
     ===================================================================
-->
```
in the style map.  
```
[SectionProblem.zip](https://github.com/dita4publishers/org.dita4publishers.word2dita/files/322444/SectionProblem.zip)
```

**Comment by Boreal-Forest** [comment]
Wow!  The editor removed a bunch of stuff.  Here it is again: 

# 

So far so great! Except for one tiny little thing ...

My tag mapping inserts &lt;reference>&lt;refbody>&lt;section>s in a reference topic. But then when I get to &lt;refsyn> I want to exit the &lt;section> so that &lt;refsyn> is valid.

Just can't seem to do it. No idea why. Level setting doesn't work. Other level changing tricks don't seem to work either.

The attached ZIP includes the docx, the stylemap and the "out" I get.

The offending style map definitions start after

&lt;!-- ===================================================================
     REFERENCE Styles
     ===================================================================
-->

in the style map.

**Comment by drmacro** [comment]
I'm on holiday this week with limited internet access. I'll take a look at this when I get a chance. This may be a case that requires post processing in the "final-fixup" mode to make correct.

**Comment by Boreal-Forest** [comment]
Thanks Eliot!

Looking forward to your reply.

On Wed, Jun 22, 2016 at 9:40 AM, Eliot Kimber notifications@github.com
wrote:

> I'm on holiday this week with limited internet access. I'll take a look at
> this when I get a chance. This may be a case that requires post processing
> in the "final-fixup" mode to make correct.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dita4publishers/org.dita4publishers.word2dita/issues/24#issuecomment-227746618,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGyY6ad1PdqKC4wLr_whjd1_jxWrHOHnks5qOTtagaJpZM4I5OFd
> .

## 

---

Peter Fournier
Cell Phone:  613-795-6550
Ottawa, Canada

**Comment by drmacro** [comment]
Is this still an issue?

**Comment by drmacro** [comment]
Closing as old.
