### ISSUE TITLE
Incorrect attempt to load non-existent footnotes.xml.rels

### ISSUE THREAD

**Issue by drmacro** [dita4publishers/org.dita4publishers.word2dita#29]
The footnote.xml.rels file does not exist. Footnote references are implicit, not explicit.

**Comment by jravier** [comment]
Hi! The footnote.xml.rels file does exist... sometimes! 
See for example the Word version of the Manual to [XMLmind-w2x converter](https://www.xmlmind.com/w2x/) (an alternative to word2dita) : 
The external link in the footnote p65 is located in this file (while the internal link in the footnote p15 is not).
So this bit of code is indeed necessary.

[btw, this docx file is very good for testing and comparing conversion solutions : it has a lot of interesting Word features (index terms, bookmarks & cross-references, document properties, legends to tables and figures, etc.]
