### ISSUE TITLE
Reference to dita.catalog XML catalog fails (SourceForge issue 180)

### ISSUE THREAD

**Issue by drmacro** [dita4publishers/org.dita4publishers.word2dita#3]
The "net.sourceforge.dita4publishers.word2dita\build-word2dita.xml" contains a reference to the dita catalog like this:
  <xmlcatalog refid="dita.catalog"></xmlcatalog>
but its target is invoked from "net.sourceforge.dita4publishers.word2dita\build_transtype-word2dita.xml" using the "ant" task:
   <ant antfile="${wordToDita.dir}/build-word2dita.xml" target="word2dita">
and the "dita.catalog" id is no longer recognized, failing to produce output:
        D:\projects\eXml\frameworks\dita\DITA-OT\build.xml:53: The following error occurred while executing this line:
        D:\projects\eXml\frameworks\dita\DITA-OT\plugins\net.sourceforge.dita4publishers.word2dita\build_transtype-word2dita.xml:28: The following error occurred while executing this line:
        D:\projects\eXml\frameworks\dita\DITA-OT\plugins\net.sourceforge.dita4publishers.word2dita\build-word2dita.xml:157: The following error occurred while executing this line:
        D:\projects\eXml\frameworks\dita\DITA-OT\plugins\net.sourceforge.dita4publishers.word2dita\build-word2dita.xml:201: Reference dita.catalog not found.

**Comment by raducoravu** [comment]
I had noticed that too but somehow I think I forgot to add an issue for it.

**Comment by drmacro** [comment]
I think this is fixed.
