### ISSUE TITLE
DITA-OT-2.3.1 Graphics - Not Copying

### ISSUE THREAD

**Issue by StanDoherty** [dita4publishers/org.dita4publishers.word2dita#33]
The issue reported by Ben on the EPUB side seems to be present with docx2dita as well:
- org.dita4publishers.epub Issue #71

**Comment by drmacro** [comment]
Can you be more specific? Except for the  relpath utils there's not any code in common between those two plugins I don't think.

**Comment by StanDoherty** [comment]
Sure . . . I do not know the code, but observed that the behaviors 
seemed to be similar, if not identical.

When docx2dita encounters a linked image in a docx file, it fails to 
convert the file. I removed linked images to get the conversions working.

When docx2dita encounters an embedded image, it generates the following XML.

<p xtrc="/w:document/w:body[1]/w:p[90]" 
xtrf="file:/C:/Users/sdoherty/AppData/Local/Temp/temp20160919074514923/template_02/word/document.xml">
   <image href="graphics/svt_image2.png" width="58.64mm" height="52.29mm">
      <alt>graphics/svt_image2.png</alt>
   </image>
</p>

The command line switches that I have set specify that the converted 
image names should be prefixed with svt_\* (which they are in the XML 
code) and saved in the subfolder named ./graphics. Neither the folder 
nor the images are generated. I can post-process the images into the 
target subfolder . . .

Here's my bat.

c:\dita-ot-2.3.1_d4p\bin\dita -i 
C:\dita-ot-2.3.1_d4p_build\source\template_02.docx -o 
C:\dita-ot-2.3.1_d4p_build\output\d4p\docx2dita -f word2dita 
-Dw2d.style-to-tag-map=c:/dita-ot-2.3.1_d4p/plugins/org.dita4publishers.word2dita/xsl/svt-word-builtin-styles-style2tagmap.xml 
-Dw2d.clean.output.dir=true 
_-Dw2d.media.dir=C:\dita-ot-2.3.1_d4p_build\output\d4p\docx2dita\topics\graphics 
-Dw2d.filename.prefix=svt__

I have attached both the source and output folders as separate ZIPs.

Thanx for looking at this . . .

Stan

**Comment by drmacro** [comment]
The Word2DITA process does not automatically copy graphics. Currently you need to make that happen yourself.

But I suppose the HTML5/EPUB/HTML2 copy-graphics mechanism could be adapted to automate copying of graphics.

Part of the problem here though is the number variables--if graphics are not linked then the graphic may not be useable and not all graphic formats that occur in Word are useful in a more general context (e.g., opaque objects, Word-only binary formats, etc.)

**Comment by StanDoherty** [comment]
Thanks . . . we're not doing bi-directional conversions of the inbound 
Word content, so I have budgeted some prep and cleanup work each time we 
do an import. Correlating the names of usable stand-alone images that 
DITA needs with the XML <image> calls that D4P generates should not be a 
big deal.

If I can guinea pig some enhancements or help with testing, please let 
me know.

Stan

**Comment by drmacro** [comment]
This is not an enhancement I can work on in the short term--I'm fully booked for the next 3 weeks at least (when it rains it pours).

From an Ant standpoint you can do something really cheap which is simply to blindly copy everything from the unzipped DOCX file graphics/ directory to the output, applying normal Ant file name transforms if necessary.

The Word-to-DITA process unzips the DOCX file to a temp location so it shouldn't be a problem to figure out where that is and use it in a custom wrapper Ant script.

**Comment by StanDoherty** [comment]
Great suggestion . . . thanks.

It's all about /temp. :-)

Stan

**Comment by drmacro** [comment]
Closing as old.
