### ISSUE TITLE
Plugin requirements and submodules

### ISSUE THREAD

**Issue by stefan-jung** [dita4publishers/org.dita4publishers.word2dita#35]
Hi Eliot,

**org.dita4publishers.word2dita** declares two requirements:

```xml
<require plugin="org.dita4publishers.doctypes"/> 
<require plugin="org.dita-community.common.xslt"/>
```

**org.dita-community.common.xslt** is a submodule, **org.dita4publishers.doctypes** is not. Should it?

**Comment by stefan-jung** [comment]
I cannot install the plugin with the `dita --install` command because of the **org.dita-community.common.xslt** Git submodule. It would be nice, if you would remove the submodule.

**Comment by paperdigits** [comment]
Can you just `git clone --recursive`  into the plugins directory and then run the integrator ant task?

**Comment by stefan-jung** [comment]
Yes, this works. But it is weird, that many plugins need a specific install routine.

**Comment by paperdigits** [comment]
I believe if you use the packaged "release" version then the submodule is included. I don't think this repo has caught up to the toolkit's new install process.

**Comment by stefan-jung** [comment]
Yes, probably. I'll close the issue.
