### ISSUE TITLE
lookupStyleName(): No style definition found for style ID "entry"

### ISSUE THREAD

**Issue by sharkvan** [dita4publishers/org.dita4publishers.word2dita#36]
lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"

I have tried to look through the word document for a item using a style id of "entry", but I could not find one. So, I'm confused as to what this error is.

Is this something that I need to fix in my mapping file or the document?

**Comment by drmacro** [comment]
This is from the handling of tables. You should be able to ignore the message.

**Comment by sharkvan** [comment]
Ok thanks for your help.

**Comment by drmacro** [comment]
Closing as not a bug.
