### ISSUE TITLE
Can't map procedure steps

### ISSUE THREAD

**Issue by paperdigits** [dita4publishers/org.dita4publishers.word2dita#39]
I'm trying to map into a task topic, following the code from here: http://www.dita4publishers.org/d4p-users-guide/user_docs/d4p-users-guide/word2dita/common-mapping-cases.html

However, I can't for the life of me get the Word style "notes" to map into the "note" element with a parent element "info." When I run the transformation in OT 1.8.5 with the latest D4P plugin release, I see the info element, but the note element does not come through. Changing "note" to another element, e.g. "p" doesn't work either. 

I've attached a docx file that illustrates the problem along with the tag map file. 

Any advice is appreciated
[Word2DITA_error.zip](https://github.com/dita4publishers/org.dita4publishers.word2dita/files/2320165/Word2DITA_error.zip)

.

**Comment by drmacro** [comment]
I don't think it's possible to do with style-to-tag mapping alone. The best I can get is step/info/note in a separate step using this mapping:

```

<paragraphStyle styleName="steps"
  structureType="dt"
  dlEntryType="step"
  containerType="steps"
  tagName="cmd"
  level="1"
/>


<paragraphStyle styleName="notes"
  structureType="dt"
  dlEntryType="info"
  containerType="steps"
  tagName="note"
  level="1"
  topicZone="body"
/>
```

Which results in this:

```
<steps xtrc="/w:document/w:body[1]/w:p[4]">
      <step xtrc="/w:document/w:body[1]/w:p[4]">
        <cmd xtrc="/w:document/w:body[1]/w:p[4]" xtrf="">Step one</cmd>
      </step>
      <info xtrc="/w:document/w:body[1]/w:p[5]"><note xtrc="/w:document/w:body[1]/w:p[5]" xtrf=""
          >Note: I am a note</note></info>
      <step xtrc="/w:document/w:body[1]/w:p[6]">
        <cmd xtrc="/w:document/w:body[1]/w:p[6]" xtrf="">Step Two</cmd>
      </step>
      <info xtrc="/w:document/w:body[1]/w:p[7]"><note xtrc="/w:document/w:body[1]/w:p[7]" xtrf=""
          >NOTE: Step three is wrong! </note></info>
      <step xtrc="/w:document/w:body[1]/w:p[8]">
        <cmd xtrc="/w:document/w:body[1]/w:p[8]" xtrf="">Step three</cmd>
      </step>
      <step xtrc="/w:document/w:body[1]/w:p[9]">
        <cmd xtrc="/w:document/w:body[1]/w:p[9]" xtrf="">Step four</cmd>
      </step>
      <step xtrc="/w:document/w:body[1]/w:p[10]">
        <cmd xtrc="/w:document/w:body[1]/w:p[10]" xtrf="" id="cmd__GoBack">Step 5</cmd>
      </step>
    </steps>
```

Thus I think post processing is required to merge the steps.

**Comment by drmacro** [comment]
Closing as old.
