### ISSUE TITLE
Merged cells cause columns count error

### ISSUE THREAD

**Issue by jdwinfodesign** [dita4publishers/org.dita4publishers.word2dita#87]
Given a Word table with two consecutive instances of merged cells any column, I get the following error: The number of table columns determined from the table structure (5) is different than the value of the "cols" attribute (4).

Merging cells down in Word works fine, as long as this is not done in two consecutive rows, whether in the first column or not

[table_issues.docx](https://github.com/dita4publishers/org.dita4publishers.word2dita/files/7730757/table_issues.docx)

Added a comment here:
https://github.com/dita4publishers/org.dita4publishers.word2dita/commit/4f29bbb2b6aa1502b804af0bcc40805aacf4c063

The attached file has a w:vMerge/w:val="restart" which is not included in the conditions to end the previous merge. If I get time, I will see whether this is the case. 

ETA: Looks like the variable followingCells in wordml2simple.xsl gets calculated by counting all following cells in the same column that have a vMerge. The error seems to be caused by the cell in the same column that has a vMerge, but it also has the restart which should be another condition for stopping the count of followingCells. I think.

**Comment by drmacro** [comment]
You are using old code. 

This bug has been fixed already. When I process your DOCX with the latest code on develop branch I get correct tables.

**Comment by jdwinfodesign** [comment]
Sorry for any inconvenience. My mistake.
